### ISSUE TITLE
TypeError: _a.isText is not a function

### ISSUE THREAD

**Issue by Ativ3k** [utarwyn/discord-tictactoe#327] opened 2022-09-03 03:47 UTC
**Describe the bug**
Error after slashcommand

**To Reproduce**
1. Use slashcommand /tictactoe

**Expected behavior**
Start game

**Versions**
discord.js@14.1.2
discord-tictactoe@3.1.0

**Screenshots**
![image](https://user-images.githubusercontent.com/63321725/188254605-6e45dd63-02da-4e7b-8c5c-7ed6c84dcfda.png)

**Additional context**
^

**Comment by utarwyn** [comment] 2022-09-03 07:47
Hello, the module does not support **discord.js v14** yet.
Check the table with supported versions in the project readme: https://github.com/utarwyn/discord-tictactoe#installation
Duplicate of issue #311.

**Comment by utarwyn** [comment] 2022-09-07 20:26
Version 4.0.0 of the module is now out with the support of **discord.js v14** 👍
More info on the release here: https://github.com/utarwyn/discord-tictactoe/releases/tag/v4.0.0

**Closed by utarwyn** 2022-09-07 20:26 UTC
Labels: bug: confirmed, status: duplicate
