### ISSUE TITLE
AI Difficulty Options

### ISSUE THREAD

**Issue by CoolDCB** [utarwyn/discord-tictactoe#333] opened 2022-09-10 19:52 UTC
**Is your feature request related to a problem? Please describe.**
It is rather annoying that it is next to impossible to win against the AI.

**Describe the solution you'd like**
Some difficulty levels for playing against the AI (eg. easy=completely random, medium=random choice between random and calculated placement, hard=fully calculated placement)
You could make my example more complicated and change it to a number (eg. if 0 then 0% of moves are calculated, if 6 then 60% (chance) of moves are calculated, up to 10 where all moves are calculated)

**Comment by utarwyn** [comment] 2022-09-11 11:17
Hello! Thank you for the idea. Its a duplicate of issue #36 I think. This is a long-standing request of addition to the module but it is also one of the most complex to do.

**Comment by CoolDCB** [comment] 2022-09-11 16:25
> Hello! Thank you for the idea. Its a duplicate of issue #36 I think. This is a long-standing request of addition to the module but it is also one of the most complex to do.

I would disagree! I explained really quite easy ways of doing this, you can simply implement whether AI chooses the next move or whether the next move is randomly generated!

**Closed** 2023-01-19 19:33 UTC
Labels: status: duplicate, type: enhancement
