### ISSUE TITLE
.isCommand() function no longer works

### ISSUE THREAD

**Issue by CoolDCB** [utarwyn/discord-tictactoe#311] opened 2022-08-20 13:54 UTC
**Describe the bug**
DiscordJS v14 removed .isCommand() in v14 so the code doesn't work properly.

**To Reproduce**
1. attempt to use discord-tictactoe in discordjs v14

**Versions**
discord-tictactoe version: 3.0.0
discord.js version: 14.0.1
Node.js version: v16.16.0

**Screenshots**
![image](https://user-images.githubusercontent.com/55620516/185749424-122f0163-ff82-4b26-8f11-2891c3a00442.png)

**Comment by utarwyn** [comment] 2022-08-21 23:24
Hello @CoolDCB, **discord-tictactoe v3 does not support discord.js v14** because of breaking changes in its API.
A nice contributor worked on this support in #276 and I will release version 4 of the module soon.
Duplicate of issue #287.

**Comment by CoolDCB** [comment] 2022-08-28 16:18
My apologies, I didn't spot that. Do you have an eta for the release date of the version?

**Comment by Gorniaky** [comment] 2022-08-31 10:43
14.2.0 back with `isCommand()`

**Comment by utarwyn** [comment] 2022-09-03 08:13
> My apologies, I didn't spot that. Do you have an eta for the release date of the version?

@CoolDCB I would like to release **version 4** next week!

**Comment by utarwyn** [comment] 2022-09-07 20:27
Version 4.0.0 of the module is now out with the support of **discord.js v14** 👍
More info on the release here: https://github.com/utarwyn/discord-tictactoe/releases/tag/v4.0.0

**Closed by utarwyn** 2022-09-07 20:27 UTC
Labels: bug: confirmed, status: duplicate
